config/routes.rb
Hookah::Application.routes.draw do
  

  get "sessions/new"

  post "sessions/create"

  delete "sessions/destroy"

  resources :users

  resources :slots

  resources :boxes

  resources :products

end

app/models/slot.rb
class Slot < ActiveRecord::Base
  attr_accessible :box_id, :product_id

  belongs_to :box
  belongs_to :product

  validates_presence_of :box_id, :product_id

end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @slots }
    end
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
    @slot = Slot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slot }
    end
  end

  # GET /slots/new
  # GET /slots/new.json
  def new
    @slot = Slot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slot }
    end
  end

  # GET /slots/1/edit
  def edit
    @slot = Slot.find(params[:id])
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(params[:slot])

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render json: @slot, status: :created, location: @slot }
      else
        format.html { render action: "new" }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /slots/1
  # PUT /slots/1.json
  def update
    @slot = Slot.find(params[:id])

    respond_to do |format|
      if @slot.update_attributes(params[:slot])
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot = Slot.find(params[:id])
    @slot.destroy

    respond_to do |format|
      format.html { redirect_to slots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_for(@slot) do |f| %>
  <% if @slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% @slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :box_id %><br />
    <%= f.text_field :box_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<h1>Listing slots</h1>

<table>
  <tr>
    <th>Box</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slots.each do |slot| %>
  <tr>
    <td><%= slot.box_id %></td>
    <td><%= slot.product_id %></td>
    <td><%= link_to 'Show', slot %></td>
    <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
    <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New slot</h1>

<%= render 'form' %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Box:</b>
  <%= @slot.box_id %>
</p>

<p>
  <b>Product:</b>
  <%= @slot.product_id %>
</p>


<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>